[QI2-717] remove asyncio usage from qaoa circuit
QuTech-Delft/quantuminspire2 pull request #114
Opened 2023-11-27 15:28 UTC by napocornejo

Error with this scrip was the usage of syncio

2023-11-27 19:49 UTC, oschusler requested changes

2023-11-27 19:49 UTC, oschusler commented on pyproject.toml
> +python = "^3.9"
Why did you update the version of python?

2023-11-27 19:49 UTC, oschusler commented on pyproject.toml
> +scipy = "^1.10.1"
These packages don't have to be installed in the SDK. It's up to the user whether they want/need them

2023-11-28 09:32 UTC, napocornejo commented on pyproject.toml
> +python = "^3.9"
Originally we had discussed with Marten to include another tests, which needs libraries in thus python version. Today we discussed that this seems a bit too much just to add one test. So it has been reverted.

2023-11-28 09:32 UTC, napocornejo commented on pyproject.toml
> +scipy = "^1.10.1"
Will  be reverted for the same reason as above.

2023-11-28 14:32 UTC, oschusler approved these changes

2023-11-28 14:55 UTC, merged