add local runtime
QuTech-Delft/quantuminspire2 pull request #84
Opened 2023-09-08 08:05 UTC by basvanberckel

2023-09-08 12:38 UTC, koffie requested changes

2023-09-08 12:38 UTC, koffie commented on tests/util/api/data/hqca_circuit.py
> +from typing import Any, Dict, List
This is almost a duplicate of `examples/hqca_circuit.py`. Is this just needed temporarilly and will we deduplicate this in the future, or will we have to keep maintaining two files? Running a hybrid algorithm locally should work the same as remotely, so ideally we would only need one version.

2023-09-08 12:38 UTC, koffie commented on tests/util/api/data/hqca_circuit.py
> +    class MockExecuteCircuitResult:
I think this class can go now we have the actual ExecuteCircuitResult. This class was only added because we didn't have ExecuteCircuitResults locally yet.

In fact, I do not think we even need the MockQI anymore.

2023-09-08 13:25 UTC, basvanberckel commented on tests/util/api/data/hqca_circuit.py
> +from typing import Any, Dict, List
You're right, I didn't want to change the existing example, but I've replaced it with a version that works with the local runtime

2023-09-08 13:25 UTC, basvanberckel commented on tests/util/api/data/hqca_circuit.py
> +    class MockExecuteCircuitResult:
Removed unneeded mock classes

2023-09-11 13:08 UTC, koffie approved these changes

2023-09-11 13:25 UTC, merged